2024-04-21 10:19:18,656 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:132]
2024-04-21 10:19:19,831 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:132]
2024-04-21 10:21:54,075 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:132]
2024-04-21 10:25:13,430 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:132]
2024-04-23 07:25:50,322 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:132]
2024-04-23 21:33:17,494 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:132]
2024-04-23 21:55:58,360 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:132]
2024-04-23 21:56:02,226 ERROR: Exception on / [GET] [in E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "e:\project\heroku_flask_test\flask_h\app.py", line 56, in home
    return render_template('pages/placeholder.home.html')
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask\templating.py", line 129, in _render
    app.update_template_context(context)
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask\app.py", line 480, in update_template_context
    context.update(self.ensure_sync(func)())
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask_login\utils.py", line 405, in _user_context_processor
    return dict(current_user=_get_user())
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask_login\login_manager.py", line 376, in _load_user
    user = self._load_user_from_remember_cookie(cookie)
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask_login\login_manager.py", line 414, in _load_user_from_remember_cookie
    user_id = decode_cookie(cookie)
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask_login\utils.py", line 62, in decode_cookie
    if hmac.compare_digest(_cookie_digest(payload, key=key), digest):
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask_login\utils.py", line 380, in _cookie_digest
    return hmac.new(key, payload.encode("utf-8"), sha512).hexdigest()
  File "C:\Users\0000\AppData\Local\Programs\Python\Python310\lib\hmac.py", line 184, in new
    return HMAC(key, msg, digestmod)
  File "C:\Users\0000\AppData\Local\Programs\Python\Python310\lib\hmac.py", line 53, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
TypeError: key: expected bytes or bytearray, but got 'NoneType'
2024-04-23 21:57:33,395 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:132]
2024-04-23 22:13:11,946 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:132]
2024-04-23 22:31:22,014 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:132]
2024-04-23 22:49:37,877 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:132]
2024-04-24 00:14:39,937 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:133]
2024-04-24 00:32:46,168 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:133]
2024-04-24 00:39:52,665 ERROR: Exception on /admin/tema_test_ad/2864 [GET] [in E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "e:\project\heroku_flask_test\flask_h\admin\admin.py", line 40, in tema_test_ad
    pre=find_claass(test_names[0].claass_id)
IndexError: list index out of range
2024-04-24 00:40:19,290 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:133]
2024-04-24 00:40:35,513 ERROR: Exception on /admin/tema_test_ad/2864 [GET] [in E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "e:\project\heroku_flask_test\flask_h\admin\admin.py", line 40, in tema_test_ad
    pre=find_claass(test_names[0].claass_id)
IndexError: list index out of range
2024-04-24 00:58:09,358 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:133]
2024-04-24 00:58:50,040 ERROR: Exception on /uroki/page_test/1/ [GET] [in E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: user_test.num_quest

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "e:\project\heroku_flask_test\flask_h\uroki\uroki.py", line 101, in page_test
    tata=find_vid(users_id, tema_test_id, test.id)
  File "e:\project\heroku_flask_test\flask_h\models\models.py", line 120, in find_vid
    user_test_record = User_test.query.filter_by(users_id=users_id, tema_test_id=tema_test_id, test_id=test_id).first()
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\sqlalchemy\orm\query.py", line 2748, in first
    return self.limit(1)._iter().first()  # type: ignore
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\sqlalchemy\orm\query.py", line 2847, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 2308, in execute
    return self._execute_internal(
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 2190, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\sqlalchemy\orm\context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1848, in _execute_context
    return self._exec_single_context(
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "E:\project\heroku_flask_test\flask_h\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: user_test.num_quest
[SQL: SELECT user_test.id AS user_test_id, user_test.num_quest AS user_test_num_quest, user_test.users_id AS user_test_users_id, user_test.tema_test_id AS user_test_tema_test_id, user_test.test_id AS user_test_test_id, user_test.vid AS user_test_vid, user_test.pr_vid AS user_test_pr_vid, user_test.date_completed AS user_test_date_completed 
FROM user_test 
WHERE user_test.users_id = ? AND user_test.tema_test_id = ? AND user_test.test_id = ?
 LIMIT ? OFFSET ?]
[parameters: (4, 1, 1, 1, 0)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-04-24 21:20:16,028 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:133]
2024-04-24 21:22:26,426 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:133]
2024-04-24 21:22:42,081 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:133]
2024-04-24 21:26:59,396 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:133]
2024-04-24 21:31:50,931 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:133]
2024-04-24 21:52:27,714 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:133]
2024-04-24 21:56:30,624 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:133]
2024-04-25 00:08:59,031 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:126]
2024-04-25 00:09:15,717 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:126]
2024-04-25 00:14:32,977 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:126]
2024-04-25 00:17:55,264 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:126]
2024-04-25 00:18:19,638 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:126]
2024-04-25 00:18:35,031 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:126]
2024-04-25 00:20:39,538 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:128]
2024-04-25 00:20:53,872 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:128]
2024-04-25 00:23:40,381 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:128]
2024-04-25 00:33:08,352 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:128]
2024-04-25 00:36:02,564 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:128]
2024-04-25 00:36:18,606 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:128]
2024-04-25 00:40:23,122 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:128]
2024-04-25 00:41:00,563 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:128]
2024-04-25 00:41:24,622 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:128]
2024-04-25 00:41:39,139 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:128]
2024-04-25 00:44:11,597 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:126]
2024-04-25 00:45:36,327 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:126]
2024-04-25 00:46:46,708 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:126]
2024-04-25 00:50:53,810 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:132]
2024-04-25 00:52:52,896 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:137]
2024-04-25 00:53:10,529 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:137]
2024-04-25 01:01:56,296 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:137]
2024-04-25 01:02:11,093 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:137]
2024-04-25 01:07:28,048 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:137]
2024-04-25 02:48:56,718 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:137]
2024-04-25 02:49:10,216 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:137]
2024-04-25 12:26:35,717 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:136]
2024-04-25 12:31:06,845 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:134]
2024-04-25 12:33:46,643 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:133]
2024-04-25 12:34:03,637 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:133]
2024-04-25 12:37:48,382 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:148]
2024-04-25 12:38:31,278 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:148]
2024-04-25 12:42:41,898 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:153]
2024-04-25 12:45:46,742 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:153]
2024-04-25 12:48:13,557 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:153]
2024-04-25 12:48:29,571 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:153]
2024-04-25 12:54:10,329 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:153]
2024-04-25 12:54:25,692 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:153]
2024-04-25 12:58:35,258 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:153]
2024-04-25 13:00:41,828 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:153]
2024-04-25 13:00:58,459 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:153]
2024-04-25 13:55:20,570 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:153]
2024-04-25 13:55:34,297 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:153]
2024-04-25 13:59:42,054 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:133]
2024-04-25 14:01:19,357 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:133]
2024-04-25 14:02:43,915 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:133]
2024-04-25 14:03:03,953 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:133]
2024-04-25 14:08:25,564 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:133]
2024-04-25 14:08:42,893 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:133]
2024-04-25 14:12:02,571 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:133]
2024-04-25 14:12:50,500 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:133]
2024-04-25 14:13:08,057 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:133]
2024-04-25 14:50:06,591 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:133]
2024-04-25 14:51:02,729 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:133]
2024-04-25 14:52:55,258 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:133]
2024-04-25 14:56:00,950 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:133]
2024-04-25 15:03:45,039 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:134]
2024-04-25 15:07:32,740 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:134]
2024-04-25 15:07:47,509 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:134]
2024-04-25 15:09:51,163 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:134]
2024-04-25 15:16:43,633 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:137]
2024-04-25 15:19:17,163 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:139]
2024-04-25 15:27:40,411 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:139]
2024-04-25 15:31:26,480 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:140]
2024-04-25 15:32:23,982 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:140]
2024-04-25 15:35:52,818 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:140]
2024-04-25 15:39:33,983 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:151]
2024-04-25 15:42:49,883 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:151]
2024-04-25 15:43:09,861 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:151]
2024-04-25 15:48:11,864 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:151]
2024-04-25 15:50:53,012 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:151]
2024-04-25 15:55:23,418 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:151]
2024-04-25 15:57:21,863 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:157]
2024-04-25 15:59:52,594 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:157]
2024-04-25 16:03:24,073 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:149]
2024-04-25 16:03:43,343 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:149]
2024-04-25 16:09:28,140 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:147]
2024-04-25 16:19:45,785 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:147]
2024-04-25 16:21:49,913 INFO: errors [in e:\project\heroku_flask_test\flask_h\app.py:147]
